# Generated by Django 3.1.7 on 2021-06-05 05:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0005_auto_20210517_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FamilyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ParentsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('consent', models.BooleanField()),
                ('name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
                ('pincode', models.IntegerField()),
                ('no_of_family_members', models.IntegerField()),
                ('children_count', models.IntegerField()),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.city')),
                ('edu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.education')),
                ('occupation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.occupation')),
            ],
        ),
        migrations.CreateModel(
            name='ReligiousBelief',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('religion_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Register',
        ),
        migrations.AddField(
            model_name='parentsinfo',
            name='religion_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.religiousbelief'),
        ),
        migrations.AddField(
            model_name='parentsinfo',
            name='state_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.state'),
        ),
        migrations.AddField(
            model_name='parentsinfo',
            name='type_of_family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.familytype'),
        ),
        migrations.AddField(
            model_name='parentsinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
