# Generated by Django 3.1.7 on 2021-06-05 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_auto_20210605_1042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parentsinfo',
            old_name='city_id',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='parentsinfo',
            old_name='edu_id',
            new_name='edu',
        ),
        migrations.RenameField(
            model_name='parentsinfo',
            old_name='occupation_id',
            new_name='occupation',
        ),
        migrations.RenameField(
            model_name='parentsinfo',
            old_name='state_id',
            new_name='state',
        ),
        migrations.AlterField(
            model_name='parentsinfo',
            name='consent',
            field=models.BooleanField(default=True),
        ),
    ]
