# Generated by Django 3.1.7 on 2021-06-05 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_auto_20210605_1047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parentsinfo',
            old_name='religion_id',
            new_name='religion',
        ),
    ]
