# Generated by Django 3.1.7 on 2021-06-05 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_auto_20210605_1049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='religiousbelief',
            old_name='religion_id',
            new_name='religion',
        ),
    ]
