# Generated by Django 3.2.4 on 2021-06-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0015_auto_20210607_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentsinfo',
            name='email',
            field=models.BinaryField(max_length=500),
        ),
        migrations.AlterField(
            model_name='parentsinfo',
            name='name',
            field=models.BinaryField(max_length=500),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.BinaryField(max_length=500),
        ),
    ]
