# Generated by Django 3.2.4 on 2021-06-08 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0017_auto_20210607_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentsinfo',
            name='first_password',
            field=models.CharField(default='helloworld14', max_length=20),
        ),
        migrations.AddField(
            model_name='parentsinfo',
            name='password_changed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentsinfo',
            name='first_password',
            field=models.CharField(default='helloworld14', max_length=20),
        ),
        migrations.AddField(
            model_name='studentsinfo',
            name='password_changed',
            field=models.BooleanField(default=False),
        ),
    ]
