# Generated by Django 3.2.3 on 2021-06-10 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0019_auto_20210609_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('tennis', models.CharField(max_length=255)),
                ('cricket', models.CharField(max_length=255)),
                ('chess', models.CharField(max_length=255)),
                ('food', models.CharField(max_length=255)),
                ('drinks', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='teacherincharge',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.school'),
        ),
    ]
