# Generated by Django 3.1.7 on 2021-06-11 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0020_auto_20210610_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='education',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='familytype',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='firstmodule',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='occupation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='parentsinfo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='religiousbelief',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='school',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='state',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='studentsinfo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='teacherincharge',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='ModuleOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draft', models.BooleanField()),
                ('nutriGarden', models.BooleanField()),
                ('source_fruits_vegetables', models.CharField(max_length=255)),
                ('grow_own_food', models.CharField(max_length=255)),
                ('if_grow_what', models.CharField(default='NA', max_length=255)),
                ('reason_gardenening', models.CharField(max_length=255)),
                ('healthy_diet', models.CharField(max_length=255)),
                ('imp_nutrients', models.CharField(max_length=255)),
                ('citrus_fruits_blank', models.CharField(max_length=255)),
                ('not_richsource_iron', models.CharField(max_length=255)),
                ('source_vitaminA', models.CharField(max_length=255)),
                ('imp_eat_fruits_vegetables', models.CharField(max_length=255)),
                ('reason_wide_variety_food', models.CharField(max_length=255)),
                ('microgreen', models.CharField(max_length=255)),
                ('microgreen_example', models.CharField(max_length=255)),
                ('harvestdays_microgreen', models.CharField(max_length=255)),
                ('microgreen_grow_seeds_kitchen', models.CharField(max_length=255)),
                ('microgreen_nutritiousthan_fullgrownvegetables', models.CharField(max_length=255)),
                ('microgreen_immunity', models.CharField(max_length=255)),
                ('microgreen_variety', models.CharField(max_length=255)),
                ('microgreen_source', models.CharField(max_length=255)),
                ('newspaper_grow_microgreen', models.CharField(max_length=255)),
                ('microgreen_first_step', models.CharField(max_length=255)),
                ('soaking_time_seeds', models.CharField(max_length=255)),
                ('microgreen_watering', models.CharField(max_length=255)),
                ('microgreen_use', models.CharField(max_length=255)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.studentsinfo')),
            ],
        ),
    ]
