# Generated by Django 3.2.4 on 2021-06-11 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0021_auto_20210611_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moduleone',
            name='reason_gardenening',
        ),
        migrations.AddField(
            model_name='moduleone',
            name='reason_gardening',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='education',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='familytype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='firstmodule',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='moduleone',
            name='citrus_fruits_blank',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='moduleone',
            name='grow_own_food',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='moduleone',
            name='harvestdays_microgreen',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='moduleone',
            name='healthy_diet',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='moduleone',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='moduleone',
            name='if_grow_what',
            field=models.CharField(default='NA', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='moduleone',
            name='imp_eat_fruits_vegetables',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='moduleone',
            name='imp_nutrients',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='moduleone',
            name='microgreen',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='moduleone',
            name='microgreen_example',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='moduleone',
            name='microgreen_first_step',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='moduleone',
            name='microgreen_grow_seeds_kitchen',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='moduleone',
            name='microgreen_immunity',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='moduleone',
            name='microgreen_nutritiousthan_fullgrownvegetables',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='moduleone',
            name='microgreen_source',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='moduleone',
            name='microgreen_use',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='moduleone',
            name='microgreen_variety',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='moduleone',
            name='microgreen_watering',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='moduleone',
            name='newspaper_grow_microgreen',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='moduleone',
            name='not_richsource_iron',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='moduleone',
            name='nutriGarden',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='moduleone',
            name='reason_wide_variety_food',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='moduleone',
            name='soaking_time_seeds',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='moduleone',
            name='source_fruits_vegetables',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='moduleone',
            name='source_vitaminA',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='occupation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='parentsinfo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='religiousbelief',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='school',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='state',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='studentsinfo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='teacherincharge',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
