# Generated by Django 3.2.4 on 2021-06-11 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0022_auto_20210611_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleone',
            name='nutriGarden',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
