# Generated by Django 3.2.3 on 2021-06-23 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0027_moduleone_pre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleone',
            name='submission_timestamp',
            field=models.DateTimeField(),
        ),
    ]
